### ISSUE TITLE
Implement controller/swarm interface function

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2171]
## Problem

Issue #2170 adds a skeleton API function for the swarm layer.  This function needs implementing.  This function will likely just call through to the new `NetworkBehaviour` and as such cannot be done until it is completed.

This ticket cannot be done until:
- `NetworkBehaviour` is done in order to execute the communication protocols

## Goal

Connect the controller/swarm API to the underlying swarm (`NetworkBehaviour`).

**Comment by thomaseizinger** [comment]
@tcharding can you please sort out the overlap between this issue and https://github.com/comit-network/comit-rs/issues/2113?

Not sure how it affects https://github.com/comit-network/comit-rs/issues/2170, but maybe worth giving it a thought.

**Comment by tcharding** [comment]
> @tcharding can you please sort out the overlap between this issue and #2113?

Done.

**Comment by thomaseizinger** [comment]
I am afraid the current proposal is still not going to work :(

> Save swap to the database
> Call the COMIT core to spawn the swap

`NetworkBehaviour` has an event-based API. It will call the `handle_event` function once the underlying implementation produces an event. That means there is not a single fn that accepts the data for announcing a swap and then saves it to the database.

The saving to the database and spawning will have to be the in the event handler, similar to what we are currently doing:

Sending request: https://github.com/comit-network/comit-rs/blob/4fd1876491f2d46722def2f68f8c99f15e9fdd82/cnd/src/network/mod.rs#L243-L250

Event handler: https://github.com/comit-network/comit-rs/blob/4fd1876491f2d46722def2f68f8c99f15e9fdd82/cnd/src/network/mod.rs#L243-L250

I guess our new code is going to be similar with the difference that what we receive in the event is a finalized swap and not something that is pending.

**Comment by bonomat** [comment]
@D4nte : you moved this into To-Refine, can you please assign someone aswell please?

**Comment by tcharding** [comment]
If its meant to be me refining it I'm not sure what more I can say about this right now.  From my understanding it describes exactly what we want.

**Comment by D4nte** [comment]
Apologies for lack of details on that. Let's bring it back to grooming and rediscuss there. Is the lack of recommendation intentional?

**Comment by tcharding** [comment]
> Apologies for lack of details on that. Let's bring it back to grooming and rediscuss there. Is the lack of recommendation intentional?

I typically do not add a `Recommendation` section unless I have something valuable to add :) I'd prefer to leave it up to the developer that picks up the ticket than make comments that are not well thought out or super beneficial.

**Comment by thomaseizinger** [comment]
I think we will at least do parts of this now, I would be in favor of closing it and opening new tickets once we see the state and know what is missing :)
